twitter_app_consumer_key: 'QaE9VnSEHoBBatlaoDYHQ'
twitter_app_consumer_secret: 'eYiTc5i38B2OVCCVzaGYejoPNgmOymrDs0tQUZyZOs'
facebook_app_id: '	129294200533457'
facebook_app_secret: '6bab1a90d498ebf364e4b6727bd25b56'
